In [22]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib.slim.python.slim.data import parallel_reader

In [3]:
tf.add_n?

In [6]:
a = tf.constant([2, 3])
b = tf.constant([4, 4])
total = tf.add_n([a, b])
sess = tf.Session()
sess.run(total)

array([6, 7], dtype=int32)

In [12]:
tf.summary.scalar?

In [11]:
tf.GraphKeys.SUMMARIES

'summaries'

In [13]:
slim = tf.contrib.slim

In [18]:
init_precision = [.999]
precision = tf.cast(init_precision, dtype=tf.float64)
precision

<tf.Tensor 'Cast_1:0' shape=(1,) dtype=float64>

In [19]:
sess.run(precision)

array([0.99900001])

In [20]:
precision = tf.concat([precision, [0.]], axis=0)
sess.run(precision)

array([0.99900001, 0.        ])

In [23]:
for t in np.arange(0., 1.1, 0.1):
    print(t)

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6000000000000001
0.7000000000000001
0.8
0.9
1.0


In [29]:
mask = tf.greater_equal(a, b)
sess.run([mask, a, b])

[array([False, False]), array([2, 3], dtype=int32), array([4, 4], dtype=int32)]

In [14]:
import sys
sys.path.append('..')

from enum import Enum
from datasets import dataset_factory

class Flags():
    dataset_name = 'pascalvoc_2007'
    dataset_split_name = 'test'
    dataset_dir = '/home/paperspace/SSD-Tensorflow/tfrecords/'

FLAGS = Flags()

print(FLAGS.dataset_name, FLAGS.dataset_split_name, FLAGS.dataset_dir)

dataset = dataset_factory.get_dataset(
            FLAGS.dataset_name, FLAGS.dataset_split_name, FLAGS.dataset_dir)

pascalvoc_2007 test /home/paperspace/SSD-Tensorflow/tfrecords/


In [16]:
data_sources = dataset.data_sources

parallel_reader.get_data_files(data_sources)

ValueError: No data files found in /home/paperspace/SSD-Tensorflow/tfrecords/voc_2007_test_*.tfrecord

In [ ]:
EVAL_DIR=./logs/
CHECKPOINT_PATH=./checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
python eval_ssd_network.py \
    --eval_dir=${EVAL_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --batch_size=1